spring.application.name=member-preferences-service

# Jackson
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.jackson.default-property-inclusion=non_null

# Actuator
management.endpoints.web.exposure.include=health,info,openapi,swagger-ui,configprops,metrics

# Springdoc
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.pattern.console=
